import json
from pathlib import Path

from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from pydantic import BaseModel

from llm_client import call_llm, image_or_pdf_block
from guardrails import scan_for_leakage
from guardrails_contest import scan_row_editorializing, validate_excuse_usage, renumber_new_rows
from stock_excuses import STOCK_EXCUSES, category_enum, category_choices_text, excuses_block_for

app = FastAPI(title="MinLaw SCT Assistant API", version="1.1")

# Enable CORS so the extension can talk to this backend.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# NOTE: this repo is currently flat (no backend/ or docs/prompts/ subfolders
# yet — see CLAUDE.md "Repo layout"), so all prompt files and test pages are
# loaded from right next to this main.py.
BASE_DIR = Path(__file__).resolve().parent


@app.get("/", response_class=HTMLResponse)
async def serve_test_ui():
    """Plain test-chat page for Feature 1 — not the Chrome extension."""
    return (BASE_DIR / "index.html").read_text(encoding="utf-8")


@app.get("/contest-evidence", response_class=HTMLResponse)
async def serve_contest_evidence_ui():
    """Standalone demo page covering the full vertical slice: Prompt 1 ->
    evidence list -> category confirmation -> contest-evidence rows. Not
    the Chrome extension UI — a same-origin page so there's something to
    click through today without the extension's frontend being finished."""
    return (BASE_DIR / "contest-evidence.html").read_text(encoding="utf-8")


def load_prompt(filename: str) -> str:
    return (BASE_DIR / filename).read_text(encoding="utf-8")


ISSUE_DISTILLATION_PROMPT = load_prompt("issue-distillation.md")
EVIDENCE_LIST_PROMPT = load_prompt("evidence-list.md")
INFER_CATEGORY_PROMPT_TEMPLATE = load_prompt("infer-category.md")
CONTEST_EVIDENCE_PROMPT_TEMPLATE = load_prompt("contest-evidence.md")

# Kept from the original prototype for the later structured-interview feature.
SCT_SYSTEM_PROMPT = """
You are a neutral structuring assistant for self-represented persons (SRPs) navigating the Small Claims Tribunals (SCT) of Singapore under the State Courts.

Your objective is to help users organize their facts, evidence, and claims while strictly mitigating confirmation bias and hallucinations. You must adhere to the following operational boundaries:

1. JURISDICTION & BOUNDARIES:
- The SCT default claim limit is S$20,000, which can rise to S$30,000 if both parties sign a Memorandum of Consent.
- Eligible disputes include contracts for the sale of goods, provision of services, residential tenancies not exceeding 2 years, and property damage (excluding motor vehicle accidents).
- Employment claims, neighbour disputes, and claims exceeding the financial cap do not belong in the SCT. Explicitly flag if a user's claim falls outside these parameters.

2. BEHAVIOR & TONE:
- Maintain strict neutrality. Never validate a user's assumptions or tell them they will win or lose.
- Ask clarifying questions one at a time to gather timeline details, monetary amounts, and physical evidence (e.g., invoices, text logs, receipts).
- Do not cite fake case laws or external statutes. Stick strictly to the parameters of the Small Claims Tribunals Act 1984.

3. COMPLIANCE & DISCLAIMER MANDATE:
- In accordance with the Singapore Judiciary's Guide on the Use of Generative AI Tools by Court Users (Registrar's Circular No. 1 of 2024), remind the user that generative AI is only an organizational tool and they bear ultimate legal responsibility for accuracy.
- Never use inverted commas or decorative quotation marks around arbitrary jargon; state requirements directly and explain them clearly in plain language.
"""

COMPLIANCE_NOTICE = "Generated output requires independent human verification pursuant to Singapore Court guidelines."

# Fixed disclaimer for the contest-evidence step — injected by the backend,
# never generated by the model. A legal disclaimer is exactly the kind of
# string you don't want subject to the model's own phrasing on any given
# call; this way it's byte-identical every time. See contest-evidence.md.
CONTEST_EVIDENCE_DISCLAIMER = (
    "This is not legal advice. It was written by an AI language model, which produces text by "
    "predicting likely words; it does not know the law, understand your case, or judge anything. "
    "What follows adds to your evidence list the documents you may be asked for if the other party "
    "disputes your claim. It is not an assessment of your claim or a prediction of the outcome."
)


class DistillRequest(BaseModel):
    user_message: str  # the full free-text account; edits/re-runs just resend this, extended


class ClaimRequest(BaseModel):
    user_message: str
    conversation_history: list[dict] = []


class EvidenceRow(BaseModel):
    row_number: int
    what_it_shows: str
    document: str
    source: str
    missing_status: str  # "no" | "no_note_it" | "yes" | "none_found"
    missing_detail: str = ""


def _files_to_blocks(files: list[UploadFile]) -> list[dict]:
    """Reads uploaded files into Messages API content blocks. Never writes
    bytes to disk, never logs filenames or contents (see CLAUDE.md privacy
    rules) — only a count is safe to log if you need to debug this."""
    blocks = []
    for f in files:
        content_type = f.content_type or "application/octet-stream"
        raw = f.file.read()
        try:
            blocks.append(image_or_pdf_block(raw, content_type))
        except ValueError as e:
            raise HTTPException(status_code=400, detail=str(e))
    return blocks


@app.post("/api/distill-issue")
async def distill_issue(payload: DistillRequest):
    """Feature 1 — Issue Distillation. Stateless: one free-text message in, one structured problem statement out."""
    try:
        # max_tokens raised from llm_client's 1024 default: the distillation
        # prompt asks for multi-section prose (facts/gap/steps per matter,
        # plus two closing blocks) which was getting cut off mid-generation
        # for anything but a very short account — surfaced as "incomplete
        # text" in the side panel. 4096 matches the other longer-output
        # endpoints below (build-evidence-list, build-contest-evidence).
        # effort dropped from llm_client's "high" default to "medium" here:
        # "high" was adding noticeable latency for a prompt that mainly
        # needs correct instruction-following (gap test, no conclusions),
        # not deep multi-step reasoning. If you see rule violations creep
        # back in (e.g. guardrail_flags showing up more often), raise this
        # back to "high" and accept the slower response instead.
        reply = call_llm(
            ISSUE_DISTILLATION_PROMPT,
            [{"role": "user", "content": payload.user_message}],
            max_tokens=4096,
            effort="medium",
        )

        flags = scan_for_leakage(reply)
        if flags:
            # Log the categories only — never the user's dispute text. See CLAUDE.md "Privacy & data handling".
            print(f"[guardrail] {len(flags)} flag(s): {[f.category for f in flags]}")

        return {
            "status": "success",
            "reply": reply,
            "guardrail_flags": [f.category for f in flags],  # internal QA field; drop before a public-facing demo if you don't want it visible
            "compliance_notice": COMPLIANCE_NOTICE,
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/api/analyze-claim")
async def analyze_claim(payload: ClaimRequest):
    """Original prototype endpoint, kept for the later structured-interview feature. Now routed through llm_client too."""
    try:
        messages = payload.conversation_history + [{"role": "user", "content": payload.user_message}]
        reply = call_llm(SCT_SYSTEM_PROMPT, messages)

        return {
            "status": "success",
            "reply": reply,
            "compliance_notice": COMPLIANCE_NOTICE,
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/api/build-evidence-list")
async def build_evidence_list(
    prompt1_output: str = Form(...),
    files: list[UploadFile] = File(default=[]),
):
    """Prompt 2 (lite) — builds the initial evidence table from Prompt 1's
    output plus any uploaded files. STUB: not present elsewhere in the repo
    as far as this build could confirm; written because Prompt 4 hard-
    depends on this table existing. Replace with the real Prompt 2 if one
    already exists elsewhere — the schema below is what Prompt 4 expects,
    so keep it compatible if you do."""
    try:
        content_blocks: list[dict] = [{"type": "text", "text": f"Claimant's restated account:\n\n{prompt1_output}"}]
        content_blocks.extend(_files_to_blocks(files))

        schema = {
            "type": "object",
            "properties": {
                "rows": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "what_it_shows": {"type": "string"},
                            "document": {"type": "string"},
                            "source": {"type": "string"},
                            "missing_status": {"type": "string", "enum": ["no", "no_note_it", "yes", "none_found"]},
                            "missing_detail": {"type": "string"},
                        },
                        "required": ["what_it_shows", "document", "source", "missing_status", "missing_detail"],
                        "additionalProperties": False,
                    },
                }
            },
            "required": ["rows"],
            "additionalProperties": False,
        }

        parsed = call_llm(
            EVIDENCE_LIST_PROMPT,
            [{"role": "user", "content": content_blocks}],
            max_tokens=2048,
            response_schema=schema,
        )

        # Backend owns row numbering from row 1, same reasoning as contest-evidence.
        rows = [
            {"row_number": i + 1, **row}
            for i, row in enumerate(parsed["rows"])
        ]

        flags = scan_for_leakage(json.dumps(rows))
        if flags:
            print(f"[guardrail] build-evidence-list: {len(flags)} flag(s): {[f.category for f in flags]}")

        return {
            "status": "success",
            "rows": rows,
            "guardrail_flags": [f.category for f in flags],
            "compliance_notice": COMPLIANCE_NOTICE,
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/api/infer-category")
async def infer_category(prompt1_output: str = Form(...)):
    """Infers which of the 9 fixed SCT categories best fits, for user
    confirmation before it's used to select a stock-excuse list. This is a
    routing decision, not a legal classification — see infer-category.md
    and the design note in chat about why this doesn't violate CLAUDE.md's
    'never classify' rule for Feature 1's own output."""
    try:
        prompt = INFER_CATEGORY_PROMPT_TEMPLATE.replace("{{CATEGORY_CHOICES}}", category_choices_text())

        schema = {
            "type": "object",
            "properties": {
                "category": {"type": "string", "enum": category_enum()},
                "reasoning": {"type": "string"},
            },
            "required": ["category", "reasoning"],
            "additionalProperties": False,
        }

        parsed = call_llm(
            prompt,
            [{"role": "user", "content": prompt1_output}],
            max_tokens=512,
            response_schema=schema,
        )

        return {
            "status": "success",
            "suggested_category": parsed["category"],
            "suggested_category_label": STOCK_EXCUSES[parsed["category"]]["label"],
            "reasoning": parsed["reasoning"],
            "all_categories": [{"key": k, "label": v["label"]} for k, v in STOCK_EXCUSES.items()],
            "compliance_notice": COMPLIANCE_NOTICE,
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/api/build-contest-evidence")
async def build_contest_evidence(
    prompt1_output: str = Form(...),
    evidence_rows_json: str = Form(...),  # JSON array, the EvidenceRow schema above, as confirmed/edited by the user
    category: str = Form(...),            # confirmed category key, e.g. "services_customer"
    files: list[UploadFile] = File(default=[]),
):
    """Prompt 4 — extends the evidence list with what the claimant may be
    asked to show if the other party disputes the claim. See
    contest-evidence.md for the full rule set."""
    if category not in STOCK_EXCUSES:
        raise HTTPException(status_code=400, detail=f"Unknown category {category!r}. Must be one of {category_enum()}")

    try:
        existing_rows = json.loads(evidence_rows_json)
    except json.JSONDecodeError:
        raise HTTPException(status_code=400, detail="evidence_rows_json must be a valid JSON array")

    next_row_number = max([r.get("row_number", 0) for r in existing_rows], default=0) + 1

    prompt = (
        CONTEST_EVIDENCE_PROMPT_TEMPLATE
        .replace("{{CATEGORY_LABEL}}", STOCK_EXCUSES[category]["label"])
        .replace("{{EXCUSES_BLOCK}}", excuses_block_for(category))
        .replace("{{NEXT_ROW_NUMBER}}", str(next_row_number))
    )

    try:
        content_blocks: list[dict] = [
            {"type": "text", "text": f"Claimant's restated account:\n\n{prompt1_output}"},
            {"type": "text", "text": f"Evidence list so far (JSON):\n\n{json.dumps(existing_rows, indent=2)}"},
        ]
        content_blocks.extend(_files_to_blocks(files))

        schema = {
            "type": "object",
            "properties": {
                "new_rows": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "row_number": {"type": "integer"},
                            "what_it_shows": {"type": "string"},
                            "document": {"type": "string"},
                            "source_type": {"type": "string", "enum": ["other_party_quote", "common_position"]},
                            "source_text": {"type": "string"},
                            "missing_status": {"type": "string", "enum": ["no", "no_note_it", "yes", "none_found"]},
                            "missing_detail": {"type": "string"},
                        },
                        "required": [
                            "row_number", "what_it_shows", "document", "source_type",
                            "source_text", "missing_status", "missing_detail",
                        ],
                        "additionalProperties": False,
                    },
                },
                "already_covered": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "position_or_excuse": {"type": "string"},
                            "covered_by_row": {"type": "integer"},
                            "note": {"type": "string"},
                        },
                        "required": ["position_or_excuse", "covered_by_row", "note"],
                        "additionalProperties": False,
                    },
                },
                "points_to_check": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "topic": {"type": "string"},
                            "official_source": {"type": "string"},
                        },
                        "required": ["topic", "official_source"],
                        "additionalProperties": False,
                    },
                },
                "inconsistencies": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "topic": {"type": "string"},
                            "version_a": {"type": "string"},
                            "version_b": {"type": "string"},
                            "instruction": {"type": "string"},
                        },
                        "required": ["topic", "version_a", "version_b", "instruction"],
                        "additionalProperties": False,
                    },
                },
                "still_cannot_show": {"type": "string"},
            },
            "required": ["new_rows", "already_covered", "points_to_check", "inconsistencies", "still_cannot_show"],
            "additionalProperties": False,
        }

        parsed = call_llm(
            prompt,
            [{"role": "user", "content": content_blocks}],
            max_tokens=3072,
            response_schema=schema,
        )

        # Backend enforces row numbering and exact-match excuse validation —
        # see guardrails_contest.py for why these are deterministic checks
        # rather than trusted model behaviour.
        parsed = renumber_new_rows(parsed, start_at=next_row_number)

        flags = []
        flags += scan_for_leakage(json.dumps(parsed))
        flags += scan_row_editorializing(parsed)
        flags += validate_excuse_usage(parsed, category)

        if flags:
            print(f"[guardrail] build-contest-evidence: {len(flags)} flag(s): {[f.category for f in flags]}")

        return {
            "status": "success",
            "disclaimer": CONTEST_EVIDENCE_DISCLAIMER,
            "new_rows": parsed["new_rows"],
            "already_covered": parsed["already_covered"],
            "points_to_check": parsed["points_to_check"],
            "inconsistencies": parsed["inconsistencies"],
            "still_cannot_show": parsed["still_cannot_show"],
            "guardrail_flags": [f.category for f in flags],
            "compliance_notice": COMPLIANCE_NOTICE,
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/health")
def health_check():
    return {"status": "healthy", "tribunal": "Small Claims Tribunals Singapore"}
